### ISSUE TITLE
Example Notebooks

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#107]
To convey the usability of GWKokab, we have to add Jupyter notebooks.

- [x] #108
- [x] #119
- [ ] Understanding the analysis by different plots and values.
- [x] #136
- [ ] How to write custom models for GWKokab in Numpyro?
- [ ] Simple article themed, "CBCs population inference for newbees", for beginners, no technicalities, just discussion.

*This list will get updates.*

**Comment by Qazalbash** [comment]
GPJax has [scripts](https://github.com/JaxGaussianProcesses/GPJax/tree/main/docs/scripts) that can convert [Python files](https://github.com/JaxGaussianProcesses/GPJax/tree/main/examples) written in a specific format to notebooks in docs. They are very clean and sleek and more importantly can be run on the cluster.
