### ISSUE TITLE
 GWKokab Model Support Expansion

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#135]
GWKokab needs to support the following models.

- [ ] Flexible Mixtures Model ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [ ] Multi-Source Model ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [ ] Multi-Spin Model ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [ ] Neutron Star Mass Models ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [ ] Power Law+Dip+Break Model ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [ ] Power Law+Spline Mass Model ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [ ] Redshift Evolution Model ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [x] Broken Power Law Mass Model
- [x] Gaussian Spin Model ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [x] Independent Spin Orientation Gaussian Isotropic ([reference](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048))
- [x] Multi Peak Mass Model
- [x] Power Law Peak Mass Model
- [x] Power Law Primary Mass Ratio
- [x] Truncated Power Law
- [x] Wysocki2019MassModel

**Comment by zeeshan5885** [comment]
Please test the Powerlaw model with Genie and Sage by making a recovery on synthetic data.
First, generate data and make a recovery using existing VT without redshift.
Secondly, after completing this [issue, ](https://github.com/gwkokab/gwkokab/issues/458) test fake data recovery with VT which also has redshift.
