### ISSUE TITLE
Convert GWKokab CLI to Class-based Interface

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#365]
Currently, GWKokab implements all analysis functionality in the `kokab` package but only exposes a CLI for interaction. Refactor the codebase to implement a proper class-based interface that can be imported and used programmatically, while maintaining CLI functionality as a wrapper.

**Desired Usage**

1. **As a Python Library**
```python
import kokab.n_pls_m_gs.sage as sage

# Initialize and configure the analyzer
analyzer = sage.Analyzer()
analyzer.func(...)
analyzer.attr = ...

# Run the analysis
analyzer.main()
```

2. **Via CLI (maintaining backward compatibility)**
```bash
playground.py \
   --args1 \
   ...
```

# Tasks
- [ ] Create a class structure for core functionality
- [ ] Move existing CLI logic into a separate wrapper
- [ ] Update documentation to reflect new usage patterns
- [ ] Add examples for both class-based and CLI usage

**Comment by Qazalbash** [comment]
Resolved in #604.
